steps:
  - name: gcr.io/cloud-builders/docker
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/__SERVICE_NAME__:${SHORT_SHA}", "."]
    dir: "app"

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/__SERVICE_NAME__"]
    dir: "app"

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "beta",
        "run",
        "deploy",
        "__SERVICE_NAME__",
        "--image",
        "gcr.io/$PROJECT_ID/__SERVICE_NAME__:${SHORT_SHA}",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
      ]
    dir: "app"
